### PR TITLE
fix(system_monitor): fix build error on tegra platform

### LINKED ISSUE #868: System_monitor build failure on Nvidia Xavier platform
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

system_monitor reported error building on Xavier.

```
--- stderr: system_monitor                                                                                                                                                   
/home/nv/ws/autoware/src/universe/autoware.universe/system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp: In member function ‘virtual void GPUMonitor::checkThrottling(diagnostic_updater::DiagnosticStatusWrapper&)’:
/home/nv/ws/autoware/src/universe/autoware.universe/system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp:130:80: error: unused parameter ‘stat’ [-Werror=unused-parameter]
  130 | void GPUMonitor::checkThrottling(diagnostic_updater::DiagnosticStatusWrapper & stat)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/gpu_monitor_lib.dir/build.make:76: CMakeFiles/gpu_monitor_lib.dir/src/gpu_monitor/tegra_gpu_monitor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:602: CMakeFiles/gpu_monitor_lib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< system_monitor [9min 1s, exited with code 2]
```

### Expected behavior

Build success

### Actual behavior

Build error

### Steps to reproduce

Build

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: main with Docker

### Possible causes

Unused variable

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Sharrrrk**
Signed-off-by: Shark Liu <shark.liu@autocore.ai>

## Description

Resolve #868 

## Related links

#868 

## Tests performed

Nvidia AGX Xavier

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

File: system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp [hunk 1]
```diff
@@ -127,8 +127,10 @@ void GPUMonitor::checkUsage(diagnostic_updater::DiagnosticStatusWrapper & stat)
   }
 }
 
-void GPUMonitor::checkThrottling(diagnostic_updater::DiagnosticStatusWrapper & stat)
+void GPUMonitor::checkThrottling(
+  [[maybe_unused]] diagnostic_updater::DiagnosticStatusWrapper & stat)
 {
+  // Please emove the [[maybe_unused]] tag after implementation, it's a temp build fix
```
Comment (wep21) [inline system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp:133]:
```suggestion
  // Please remove the [[maybe_unused]] tag after implementation, it's a temp build fix
```

**Comment by Sharrrrk** [comment]
@wep21, thank you for the fix.

**Review by ito-san — APPROVED** [review]
Thank you for the fix!
