### PR TITLE
fix(log-messages): reduce excessive log messages

### LINKED ISSUE #5539: Reduce excessive error and warning logs on Autoware launch
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

When Autoware is executed, it generates a significant number of warning and error logs, despite the system running as expected. The logs are not only excessive but also misrepresent the stability of the running application, as they appear even in the absence of actual functional issues. This creates a noisy debugging environment, making it challenging to identify and address genuine issues.

The issue was replicated using the latest `main` branch with the planning simulator demo as per the Autoware documentation: [Planning Simulation Tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/).

A video demonstrating the issue is available here:
- [Autoware Error and Warning Logs Video](https://www.youtube.com/watch?v=JDXDh1oNaMg)

The logs from the run that showcase the problem can be found here:
- [Autoware Logs Gist](https://gist.github.com/xmfcx/aebd2fe8a9a7c08a388aafae69dd110a)

### Purpose

The primary goal is to clean up the logs by either resolving the underlying causes of the warnings and errors or by adjusting the threat levels if the logs are not indicative of real issues.
This will aid in de-cluttering the console output, making it easier to debug actual problems, and generally improve the developer experience.

### Possible approaches

1. **Log Analysis**: Go through the logs to determine if the warnings/errors are justified. If they represent real issues, then they should be addressed with bug fixes.
2. **Adjust Log Levels**: If the logs are overly cautious and do not represent actual errors or critical warnings, then the log levels should be adjusted accordingly.
3. **Code Refactoring**: Inspect the sections of the code-base that are generating these logs and refactor if necessary to prevent false positives.
4. **Configuration Tweaks**: Check if the verbosity of the logs can be configured, allowing users to set the desired level of log detail.
5. **Documentation Update**: If certain logs are expected and do not indicate problems, this should be clearly documented to avoid confusion. (last resort, not preferred)
6. **Incremental Fixing**: Tackle the errors and warnings in batches, creating multiple issues or pull requests to address them systematically.

### Definition of done

- [ ] The error and warning logs that are not indicative of actual issues are eliminated or their threat levels are adjusted.
- [ ] The logging output should be clear and should accurately reflect the operational status of Autoware.
- [ ] Documentation should be updated, if necessary, to reflect any changes made to log management.
- [ ] Additional issues should be created for any unresolved logs that require further investigation or long-term changes.
- [ ] The Autoware community agrees that the logging is now informative and not excessively verbose, allowing for effective debugging.

### PR DESCRIPTION
**Pull request by ahmeddesokyebrahim**
## Description
This PR is one of group of PRs that aim to fix Autoware logging system to achieve the goal of reducing excessive error and warning logs on Autoware launch. 

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539

## Related links
More details in the [issue](https://github.com/autowarefoundation/autoware.universe/issues/5539).

### Relevant PRS
- [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/760)
- [autoware_common](https://github.com/autowarefoundation/autoware_common/pull/224)
- [tier4/pointcloud_to_laserscan](https://github.com/tier4/pointcloud_to_laserscan/pull/6)

## Tests performed
- Planning Simulation
  - Run [Autoware planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) and you can see no more excessive and recurring error, warning, and info message when the system running as expected
- Rosbag Replay Simulation
  - To be addressed in another PR
- AWSIM
  - To be addressed in another PR - extended goal)

## Notes for reviewers
Take into consideration relevant PRs.

:red_circle: **Merge Dependency** :red_circle: 
:exclamation: This PR is depending on a change in [autoware_common](https://github.com/autowarefoundation/autoware_common/pull/224) which will require the autoware_common PR to be merged firstly to have the build and test differential successful :exclamation:
## Interface changes
N.A

## Effects on system behavior
- Improved console output => better developer experience specially for debugging and catching actual problems.
- Some recurrent info messages are lowered to debug level. So the developer would need to set the logger level of that specific node to see the debug message.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
https://github.com/autowarefoundation/autoware.universe/actions/runs/7756002711/job/21152483741?pr=5971#step:2:23

The PR title and first commit message should start with lowercase letters.

`fix(log-messages): reduce excessive log messages`

You can drop "in Autoware" as well.

File: control/control_validator/src/control_validator.cpp [hunk 1]
```diff
@@ -46,14 +46,11 @@ ControlValidator::ControlValidator(const rclcpp::NodeOptions & options)
 
   setupParameters();
 
-  if (publish_diag_) {
-    setupDiag();
-  }
+  setupDiag();
```
Comment (xmfcx) [inline control/control_validator/src/control_validator.cpp:49]: Why was this `publish_diag_` parameter removed?

**Comment by xmfcx** [comment]
@ahmeddesokyebrahim can we merge this PR?

File: system/system_error_monitor/src/system_error_monitor_core.cpp [hunk 2]
```diff
@@ -374,6 +375,11 @@ void AutowareErrorMonitor::onAutowareState(
 void AutowareErrorMonitor::onControlMode(
   const autoware_auto_vehicle_msgs::msg::ControlModeReport::ConstSharedPtr msg)
 {
+  // used for indicating that onControlMode callback is trigged at least once.
```
Comment (xmfcx) [inline system/system_error_monitor/src/system_error_monitor_core.cpp:378]:
```suggestion
  // used for indicating that onControlMode callback is called at least once.
```
Small typo on the word "triggered" but I think called is ok to use here.

File: control/control_validator/src/control_validator.cpp (hunk 1 above)
Comment (ahmeddesokyebrahim) [reply control/control_validator/src/control_validator.cpp:49]: Please have a log to the [sheet](https://docs.google.com/spreadsheets/d/1z6RTyKQuaERNli5b-iCdj1ottrK84h_RUKbKmkc7YxU/edit#gid=0), warnings tab, row 22

**Comment by ahmeddesokyebrahim** [comment]
> https://github.com/autowarefoundation/autoware.universe/actions/runs/7756002711/job/21152483741?pr=5971#step:2:23
> 
> The PR title and first commit message should start with lowercase letters.
> 
> `fix(log-messages): reduce excessive log messages`
> 
> You can drop "in Autoware" as well.

@xmfcx : Thanks for the comment. This is fixed here and in other PRs as well.

File: system/system_error_monitor/src/system_error_monitor_core.cpp (hunk 2 above)
Comment (ahmeddesokyebrahim) [reply system/system_error_monitor/src/system_error_monitor_core.cpp]: Fixed

**Comment by ahmeddesokyebrahim** [comment]
:exclamation: This PR is depending on a change in [autoware_common](https://github.com/autowarefoundation/autoware_common/pull/224)which will require the autoware_common to be merged firstly to have the build and test differential successful :exclamation:

**Comment by xmfcx** [comment]
I've rebased it to see if the build error would go away. I will also build it locally to see what's up.

File: control/control_validator/src/control_validator.cpp (hunk 1 above)
Comment (xmfcx) [reply control/control_validator/src/control_validator.cpp:49]: Thanks for the clarification.

I also agree we can publish this HW_ID by default since it will complain otherwise.

@soblin @kyoichi-sugahara @takayuki5168 Do you agree? Can we remove this parameter?

**Comment by xmfcx** [comment]
Ok it was failing because this PR depends on:
- https://github.com/autowarefoundation/autoware_common/pull/224/files
this PR to be merged first.

**Comment by ahmeddesokyebrahim** [comment]
> Ok it was failing because this PR depends on:
> 
>     * [fix(log-messages): reduce excessive log messages autoware_common#224](https://github.com/autowarefoundation/autoware_common/pull/224)
>       this PR to be merged first.

@xmfcx You are totally correct. I have already highlighted that in the note for reviewer section and mentioned the merge sequence order in a [comment](https://github.com/autowarefoundation/autoware.universe/issues/5539#issuecomment-1931126414) in the issue.

There is a similar merge dependency in [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/760) as well we need to be careful of.

**Comment by xmfcx** [comment]
It compiles and works with all 3 PRs together in the planning simulator and the no unnecessary warnings or errors. Great work!

I will skim through the changes and add comments if necessary.

File: control/control_validator/src/control_validator.cpp (hunk 1 above)
Comment (kyoichi-sugahara) [reply control/control_validator/src/control_validator.cpp:49]: @ahmeddesokyebrahim @xmfcx 
Sorry for late reply and thank you so much for investigating the problem.
Yes, you cen remove the paramter :+1:

**Review by kyoichi-sugahara — APPROVED** [review]
Thanks!!!
LGTM change for control validator!

File: control/control_validator/src/control_validator.cpp (hunk 1 above)
Comment (xmfcx) [reply control/control_validator/src/control_validator.cpp:49]: cc. @mitsudome-r

File: system/system_error_monitor/src/system_error_monitor_core.cpp [hunk 3]
```diff
@@ -374,6 +375,11 @@ void AutowareErrorMonitor::onAutowareState(
 void AutowareErrorMonitor::onControlMode(
   const autoware_auto_vehicle_msgs::msg::ControlModeReport::ConstSharedPtr msg)
 {
+  // used for indicating that onControlMode callback is called at least once.
+  if (!control_mode_activated_) {
+    control_mode_activated_ = true;
+  }
+
```
Comment (xmfcx) [inline system/system_error_monitor/src/system_error_monitor_core.cpp:382]: About this one, the new `control_mode_activated_` flag:
Reference from [the sheet](https://docs.google.com/spreadsheets/d/1z6RTyKQuaERNli5b-iCdj1ottrK84h_RUKbKmkc7YxU/edit?usp=sharing) Errors sheet Row 3:
  > This error message is intended to appear when `/vehicle/status/control_mode` is no longer subscribed and not sending data to Autoware  `system_error_monitor`.
  > The error message happens when an Autoware user starts planning simulator and the vehicle start location is not set you (simulator not initialized  yet). 
  > Once the vehicle start location is set and simulator is initialized, the topic publishes data and the error goes away.

In real vehicle, this error message could be expected to be seen even when the topic is never received.

I have 2 proposals to address these:

## 1. System Error Monitor Init Phase

Allow system_error_monitor node to have an initial countdown (user can set the seconds) and It won't report anything for this period. After it ends, it will publish as usual.

This period can be set to something like 10s for planning simulator maybe.

## 2. Autoware RViz Side Panel Visualization

We could have this somehow shown as red in the future side panel for this topic.
And once this error is gone, it would turn green for this message.

(This panel issue still hasn't been created so we can skip this solution for now.)

cc. @mitsudome-r 

@ahmeddesokyebrahim for now, let's revert this change and we can create another issue to resolve this with the `system_error_monitor` node.

Comment (ahmeddesokyebrahim) [reply system/system_error_monitor/src/system_error_monitor_core.cpp]: I have reverted the proposed solution and opened an [issue](https://github.com/autowarefoundation/autoware.universe/issues/6383).

Comment (xmfcx) [reply system/system_error_monitor/src/system_error_monitor_core.cpp]: Thanks!

File: planning/behavior_velocity_traffic_light_module/src/scene.cpp [hunk 4]
```diff
@@ -199,7 +199,9 @@ bool TrafficLightModule::modifyPathVelocity(PathWithLaneId * path, StopReason *
         input_path, lanelet_stop_lines,
         planner_param_.stop_margin + planner_data_->vehicle_info_.max_longitudinal_offset_m,
         planner_data_->stop_line_extend_length, stop_line_point, stop_line_point_idx)) {
-    RCLCPP_WARN_THROTTLE(logger_, *clock_, 5000, "Failed to calculate stop point and insert index");
+    RCLCPP_WARN_STREAM_ONCE(
+      logger_, "Failed to calculate stop point and insert index for regulatory element id "
+                 << traffic_light_reg_elem_.id());
```
Comment (xmfcx) [inline planning/behavior_velocity_traffic_light_module/src/scene.cpp:204]: @shmpwk @tkimura4 @satoshi-ota are you alright with making this warn once? (Instead of every 5 seconds)

This is to reduce clutter.

File: planning/behavior_velocity_traffic_light_module/src/scene.cpp [hunk 5]
```diff
@@ -356,9 +358,9 @@ bool TrafficLightModule::findValidTrafficSignal(TrafficSignalStamped & valid_tra
   const auto traffic_signal_stamped_opt = planner_data_->getTrafficSignal(
     traffic_light_reg_elem_.id(), true /* traffic light module keeps last observation */);
   if (!traffic_signal_stamped_opt) {
-    RCLCPP_WARN_THROTTLE(
-      logger_, *clock_, 5000 /* ms */,
-      "the traffic signal data associated with regulatory element id is not received");
+    RCLCPP_WARN_STREAM_ONCE(
+      logger_, "the traffic signal data associated with regulatory element id "
+                 << traffic_light_reg_elem_.id() << " is not received");
```
Comment (xmfcx) [inline planning/behavior_velocity_traffic_light_module/src/scene.cpp:363]: @shmpwk @tkimura4 @satoshi-ota are you alright with making this warn once? (Instead of every 5 seconds)

This is to reduce clutter.

Comment (shmpwk) [reply planning/behavior_velocity_traffic_light_module/src/scene.cpp:363]: I agree to warn once either.

**Review by xmfcx — APPROVED** [review]

**Comment by ahmeddesokyebrahim** [comment]
@xmfcx , I see all required actions are passing now.
What is preventing this PR now from being ready for merge ?

**Comment by xmfcx** [comment]
> What is preventing this PR now from being ready for merge ?

Normally, we would have to get approvals from at least 1 Code Owner from each package.

But I can override it as repo maintainer.
