### PR TITLE
fix(obstacle_avoidance_planner): adding missing functionality for footprint marker

### LINKED ISSUE #4190: Adding missing PRs to obstacle_avoidance_planner since code refactoring
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

This task is to address the missing PRs in `obstacle_avoidance_planner` since code refactoring.

Refactoring PR : 
- https://github.com/autowarefoundation/autoware.universe/pull/2796#:~:text=docs%C2%A0%232963-,import%20missing%20PRs,-ee98754

Missing PRs : 
- https://github.com/autowarefoundation/autoware.universe/commit/ee9875496ff2636be8bf4a9ef1a861e984519489
- https://github.com/autowarefoundation/autoware.universe/commit/d6afa1bb7e8401586c97d9850f1caa06ac094ebd
- https://github.com/autowarefoundation/autoware.universe/commit/2d98ee84c9b422529a543922732e6f12046c0e20

### Purpose

Add the mentioned PRs to `obstacle_avoidance_planner`.

### Possible approaches

Integrate the missing pieces from the mentioned PRs into main branch

### Definition of done

- [ ] Create PR for each missing PR mentioned above
- [ ] Review & Merge PRs

### PR DESCRIPTION
**Pull request by ahmeddesokyebrahim**
## Description
This PR is to add missing functionality of footprint marker in `obstacle_avoidance_planner` since refactoring done in https://github.com/autowarefoundation/autoware.universe/pull/2796 . 

## Related links
closes #4190 

## Tests performed
Same as mentioned in original PR : https://github.com/autowarefoundation/autoware.universe/pull/2689

## Notes for reviewers
Original PR : https://github.com/autowarefoundation/autoware.universe/pull/2689
Refactoring PR : https://github.com/autowarefoundation/autoware.universe/pull/2796

## Interface changes
N.A.

## Effects on system behavior
This PR creates a separate footprint marker and appends it to `marker_array` in `obstacle_avoidance_planner` for easier debugging.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ahmeddesokyebrahim** [comment]
@mehmetdogru : May you please have a look and confirm it is doing the functionality intended as original implementation ?

File: planning/obstacle_avoidance_planner/src/node.cpp [hunk 1]
```diff
@@ -448,6 +448,7 @@ void ObstacleAvoidancePlanner::insertZeroVelocityOutsideDrivableArea(
   if (first_outside_idx) {
     for (size_t i = *first_outside_idx; i < optimized_traj_points.size(); ++i) {
       optimized_traj_points.at(i).longitudinal_velocity_mps = 0.0;
+      debug_data_ptr_->stop_pose_by_drivable_area = optimized_traj_points.at(i).pose;
```
Comment (mehmetdogru) [inline planning/obstacle_avoidance_planner/src/node.cpp:451]:
```suggestion
    debug_data_ptr_->stop_pose_by_drivable_area = optimized_traj_points.at(*first_outside_idx).pose;
    for (size_t i = *first_outside_idx; i < optimized_traj_points.size(); ++i) {
      optimized_traj_points.at(i).longitudinal_velocity_mps = 0.0;
```

**Review by mehmetdogru — CHANGES_REQUESTED** [review]

**Review by mehmetdogru — APPROVED** [review]
LGTM, thank you for the implementation

**Review by mehmetdogru — APPROVED** [review]

**Comment by ahmeddesokyebrahim** [comment]
@TakaHoribe - @kosuke55 - @takayuki5168 :
May anyone have a look please ?

File: planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp [hunk 2]
```diff
@@ -19,6 +19,8 @@
 #include "rclcpp/rclcpp.hpp"
 #include "tier4_autoware_utils/tier4_autoware_utils.hpp"
 
+#include <boost/optional.hpp>
+
```
Comment (takayuki5168) [inline planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp:23]: Could you use std::optional instead of boost::optional?

Comment (ahmeddesokyebrahim) [reply planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp]: Thanks for the proposal @takayuki5168 . I have fixed that. Please have a look.

**Review by takayuki5168 — APPROVED** [review]
